language: node_js

node_js: 10

before_install:
    - npm i -g codecov

install:
    - npm i
    - cd server && npm i

before_script:
    - cd ..

script:
    - npm run lint
    - npm run test -- -u

after_script:
    - codecov

git:
  depth: 1
